In [1]:
import sympy
import numpy as np
import scipy.fftpack
import matplotlib
import matplotlib.pyplot as plt

%matplotlib inline

plt.rcParams["font.family"] = "Source Han Sans JP"  # 使用するフォント
plt.rcParams["xtick.direction"] = "in"  # x軸の目盛線が内向き('in')か外向き('out')か双方向か('inout')
plt.rcParams["ytick.direction"] = "in"  # y軸の目盛線が内向き('in')か外向き('out')か双方向か('inout')
plt.rcParams["xtick.major.width"] = 1.0  # x軸主目盛り線の線幅
plt.rcParams["ytick.major.width"] = 1.0  # y軸主目盛り線の線幅
plt.rcParams["font.size"] = 12  # フォントの大きさ
plt.rcParams["axes.linewidth"] = 1.0  # 軸の線幅edge linewidth。囲みの太さ
matplotlib.font_manager._rebuild()
n_bar = 4
N = 8

$W^L_{k,\hat{0}} = $ W_L_k_kh[0,:] = W_L_k_kh[0]

In [2]:
W_L_k_kh = np.zeros((n_bar - 1, N))

In [3]:
x_l = (2 * np.arange(N) + 1) / (2 * N)

In [4]:
s_l = np.arange(n_bar) / (n_bar - 1)

In [5]:
xi = (np.arange(n_bar + 1) - 0.5) / (n_bar - 1)

In [6]:
def Lagrange_j(j):
    x = sympy.Symbol("x")
    L_x = 1.0
    for l in range(n_bar):
        if l != j:
            L_x *= (x - s_l[l]) / (s_l[j] - s_l[l])
    return sympy.integrate(L_x)

In [7]:
L_j = np.zeros((n_bar, N))
x = sympy.Symbol("x")
for j in range(n_bar):
    temp = []
    Lj = Lagrange_j(j)
    for k in range(N):
        temp.append(Lj.subs(x, x_l[k]))
    L_j[j] = np.array(temp)

In [8]:
w_k_j = np.zeros((n_bar, N))
for j in range(n_bar):
    w_k_j[j] = scipy.fftpack.dct(L_j[j], norm="ortho")

In [9]:
lambda_kh = np.ones(n_bar)
lambda_kh[0] = np.sqrt(1 / 2)

In [10]:
for kh in range(n_bar - 1):
    W_L_k_kh[kh] = (
        (1 - n_bar)
        * np.sqrt(2 / N)
        * lambda_kh[kh]
        * np.cos(np.pi * kh * (xi[0] + 1))
        * w_k_j[0]
    )

In [11]:
W_L_k_kh

array([[-0.32692909,  0.03508765,  0.03109297,  0.03982077,  0.01890564,
         0.01271889,  0.00664277,  0.00325798],
       [ 0.40040473, -0.04297341, -0.03808096, -0.04877029, -0.02315459,
        -0.01557739, -0.0081357 , -0.00399019],
       [-0.23117378,  0.02481071,  0.02198605,  0.02815754,  0.01336831,
         0.00899361,  0.00469715,  0.00230374]])

In [12]:
W_k_kh = np.zeros((n_bar - 1, N))

In [13]:
for kh in range(n_bar - 1):
    sum_sin = np.zeros(N)
    for j in range(1, n_bar - 2 + 1):
        sum_sin += np.sin(np.pi * kh * s_l[j]) * w_k_j[j]

    W_k_kh[kh] = (
        (n_bar - 1)
        * np.sqrt(2 / N)
        * lambda_kh[kh]
        * (
            np.cos(np.pi * kh * xi[1]) * (w_k_j[0] - (-1) ** (kh) * w_k_j[n_bar - 1])
            - 2 * np.sin((np.pi * kh) / (2 * (n_bar - 1))) * sum_sin
        )
    )

In [14]:
W_k_kh

array([[ 2.78858185e-01,  7.35980840e-17, -6.21859465e-02,
        -4.41588504e-17, -3.78112793e-02, -4.78387546e-17,
        -1.32855480e-02, -7.35980840e-18],
       [-9.18558654e-01,  8.74209233e-01, -5.27712893e-16,
        -8.57257222e-02,  3.29307249e-16, -2.96870029e-02,
         3.76073048e-16, -7.72772275e-03],
       [-1.23501460e+00,  4.84708309e-16,  8.91008562e-01,
        -3.73752751e-16,  3.09445534e-02, -1.09014206e-15,
         6.29030348e-04, -6.29591939e-16]])

In [15]:
W_R_k_kh = np.zeros((n_bar - 1, N))

In [16]:
for kh in range(n_bar - 1):
    W_R_k_kh[kh] = (
        (n_bar - 1)
        * np.sqrt(2 / N)
        * lambda_kh[kh]
        * np.cos(np.pi * kh * (xi[n_bar] - 1))
        * w_k_j[n_bar - 1]
    )

In [17]:
W_R_k_kh

array([[ 0.04807091, -0.03508765,  0.03109297, -0.03982077,  0.01890564,
        -0.01271889,  0.00664277, -0.00325798],
       [ 0.0588746 , -0.04297341,  0.03808096, -0.04877029,  0.02315459,
        -0.01557739,  0.0081357 , -0.00399019],
       [ 0.03399126, -0.02481071,  0.02198605, -0.02815754,  0.01336831,
        -0.00899361,  0.00469715, -0.00230374]])